# Generated by Django 3.1.3 on 2020-11-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojamariabonita', '0003_auto_20201123_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='CEP',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
